### ISSUE TITLE
txt2ts decimal seperator

### ISSUE THREAD

**Issue by srothmei** [nbbrd/jdemetra-cli#27]
Hey, 
we've currently encountered an issue when trying to convert a TSV-File into an XML-TS-file using the CLI tools:
When we used a point as a decimal seperator, the generated numbers in the timeries seemed to be multiplied by 10, i.e. the decimal-portion was shifted.
Once we changed our input-data to use a comma as the decimal seperator, things wen't on as expected.

We've used the following parameters calling the cli-binaries:
```
txt2ts timeseries_data.csv -o timeseries_xml.xml -f
```

Best
Simon

**Comment by charphi** [comment]
Hi,
The decimal separator is specified by the `locale` option (see `txt2ts -?`).
For example: `txt2ts data.csv --locale en`

**Comment by srothmei** [comment]
Hi,
i forgot to mention that when we used Excel-Files as an input, i.e. `spreadsheet2ts`, it was workling flawlessly using the point as decimal seperator.
But then we decided to go for TSV-files as input, without changing from `.` to `,` and the aforementioned behaviour emerged

**Comment by charphi** [comment]
This is normal since each spreadsheet cell has a data type which is used to read numerical values.
On the other hand, a TSV file is just a text file, so we have to interpret its content. The `locale` parameter specifies how a numerical value should look like.

**Comment by srothmei** [comment]
Ah okay i wasn't aware of that. So overall this is all intended behaviour and no bug at all i guess.
Hence this issue can be closed.
Anyway, thank you for the quick help on this
(and since it's the 21th of December now, happy holidays i guess)

Best
Simon
